### ISSUE TITLE
Withdrawals

### ISSUE THREAD

**Issue by farsider350** [LightBurdenOfficial/Spero-Exchange#2]

**Comment by LightBurdenOfficial** [comment]
Check the withdrawal logs.

```
log/peatio:amqp:withdraw_coin.output
log/withdraw_audit.rb.output
```

**Comment by farsider350** [comment]
log/peatio:amqp:withdraw_coin.output
[error]: undefined method `base_secret' for #<Currency:0x0055dbe3199898>

Line 58:
txid = CoinRPC[withdraw.currency].sendtoaddress withdraw.channel.currency_obj.base_secret, withdraw.fund_uid, @amount.to_f

Other repos don't use the base_secret and I couldn't find any reference to it so I removed the base_secret and got the error
[error]: wrong number of arguments (0 for 3)
 
Do I need base_secret and where do I put/get the output for it?

**Comment by LightBurdenOfficial** [comment]
As it is not an error with our repository, it is complicated to provide support ...
However as reported in the error, some argument is missing within the currency settings in the `config/currencies.yml` file

I suggest opening issues within the repository that you have cloned and are working on.

**Comment by farsider350** [comment]
You are using the same base_secret on line 50 of https://github.com/DigitalCoin1/Spero-Exchange/blob/rebuild-peatio/app/models/worker/withdraw_coin.rb
I'll happily use your repo if your suggesting it will be more beneficial but there's nothing in your currencies.yml.example that corresponds to the base_secret.
Can you supply a currencies.yml example of one coin from your working exchange please.

**Comment by DigitalCoin1** [comment]
> You are using the same base_secret on line 50 of https://github.com/DigitalCoin1/Spero-Exchange/blob/rebuild-peatio/app/models/worker/withdraw_coin.rb
> I'll happily use your repo if your suggesting it will be more beneficial but there's nothing in your currencies.yml.example that corresponds to the base_secret.
> Can you supply a currencies.yml example of one coin from your working exchange please.


```
- id: 5
  key: spero
  code: spero
  symbol: "S"
  coin: true
  family: SPERO
  coinname: Sperocoin
  coin_info: "SPEROs initial proposal is to create a currency that can be used by any user without complications and delays in transactions. We want to bring a currency that is usual in our day to day, either by an independent seller or by a large supermarket chain. The basis of this project is to help people with low or almost no income to achieve the minimum dignity possible in life in society. We want students who suffer from their high study costs to be able to make their snacks, buy books and do much more using our system at no cost."
  quick_withdraw_max: 0
  withdraw_limit: 5000
  withdraw_day_limit: 2000
  rest: http://localhost
  rpc: http://USER_RCP:PASS_RPC@IP:PORT
  proto: OLD_BTC
  blockchain: https://explorer.sperocoin.org/tx/#{txid}
  address_url: https://explorer.sperocoin.org/address/#{address}
  home: https://sperocoin.org
  btt: https://bitcointalk.org/index.php?topic=2260985.0
  be: https://explorer.sperocoin.org
  assets:
    accounts:
      -
        address: ADDRESS_SPERO
```
